#ifndef DG_CAPI_H
#define DG_CAPI_H

#pragma once

/* Generated by cbindgen; do not edit. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * ABI status returned by every fallible C entry point.
 */
typedef enum DgStatus {
  Ok = 0,
  Again = 1,
  EndOfStream = 2,
  /**
   * Engine handle is busy with another exclusive operation.
   */
  Busy = 3,
  InvalidArgument = -1,
  NullPointer = -2,
  InvalidHandle = -3,
  ParseError = -4,
  NotBuilt = -5,
  RuntimeError = -6,
  Unsupported = -7,
  Panic = -8,
  InternalError = -9,
} DgStatus;

/**
 * Lifecycle status of a running graph engine.
 */
typedef enum DgGraphStatus {
  Starting = 0,
  Running = 1,
  Draining = 2,
  Stopped = 3,
  Failed = 4,
  Reloading = 5,
  NotRunning = -1,
} DgGraphStatus;

/**
 * Logical device family.
 */
typedef enum DgDeviceKind {
  Cpu = 0,
  IntelGpu = 1,
  IntelNpu = 2,
  CudaGpu = 3,
  RknnNpu = 4,
  SophonTpu = 5,
} DgDeviceKind;

/**
 * Supported tensor element types.
 */
typedef enum DgDataType {
  U8 = 0,
  U16 = 1,
  I4 = 2,
  I8 = 3,
  I16 = 4,
  F4 = 5,
  F8 = 6,
  F16 = 7,
  Bf16 = 8,
  F32 = 9,
  F64 = 10,
  U32 = 11,
  I32 = 12,
  U64 = 13,
  I64 = 14,
} DgDataType;

/**
 * Tensor layout.
 */
typedef enum DgDataFormat {
  Auto = 0,
  N = 1,
  Nc = 2,
  Nchw = 3,
  Nhwc = 4,
  Nc4hw = 5,
  Nc8hw = 6,
  Ncdhw = 7,
  Oihw = 8,
} DgDataFormat;

/**
 * Graph serialization format.
 */
typedef enum DgGraphFormat {
  Yaml = 0,
  Json = 1,
  Toml = 2,
} DgGraphFormat;

/**
 * Imported external memory domain.
 */
typedef enum DgMemoryDomain {
  Host = 0,
  DmaBuf = 1,
  DrmPrime = 2,
  VaapiSurface = 3,
  CudaDevice = 4,
  MppBuffer = 5,
  SophonDevice = 6,
  Opaque = 7,
} DgMemoryDomain;

/**
 * Backend family for direct backend lifecycle operations.
 */
typedef enum DgBackendKind {
  Mock = 0,
  OpenVino = 1,
  Rknn = 2,
  TensorRt = 3,
  Sophon = 4,
} DgBackendKind;

/**
 * Opaque direct inference backend handle.
 */
typedef struct DgBackend DgBackend;

/**
 * Opaque buffer handle.
 */
typedef struct DgBuffer DgBuffer;

/**
 * Opaque graph engine handle.
 */
typedef struct DgEngine DgEngine;

/**
 * Opaque error handle returned by fallible v2 ABI calls. The library allocates
 * and frees it; callers must use `dg_error_free`.
 */
typedef struct DgError DgError;

/**
 * Owned byte buffer returned by v2 ABI calls. The library allocates and frees
 * it; callers must use `dg_owned_bytes_free`.
 */
typedef struct DgOwnedBytes DgOwnedBytes;

/**
 * Opaque tensor handle.
 */
typedef struct DgTensor DgTensor;

/**
 * Runtime bootstrap options for [`dg_runtime_init`].
 */
typedef struct DgRuntimeInitOptions {
  /**
   * Must be set to `size_of::<DgRuntimeInitOptions>()` by the caller.
   */
  uint32_t struct_size;
  /**
   * ABI struct version; must be 0 for the current definition.
   */
  uint32_t struct_version;
} DgRuntimeInitOptions;

/**
 * Runtime capabilities returned by a direct backend.
 */
typedef struct DgBackendCapabilities {
  /**
   * Size of this struct in bytes (`sizeof(DgBackendCapabilities)`).
   */
  uint32_t struct_size;
  /**
   * ABI struct version; must be 0 for the current definition.
   */
  uint32_t struct_version;
  size_t device_count;
  enum DgDeviceKind devices[8];
  size_t precision_count;
  enum DgDataType precisions[16];
} DgBackendCapabilities;

/**
 * Fixed-size tensor metadata returned by direct backend queries.
 */
typedef struct DgTensorInfo {
  /**
   * Size of this struct in bytes (`sizeof(DgTensorInfo)`).
   */
  uint32_t struct_size;
  /**
   * ABI struct version; must be 0 for the current definition.
   */
  uint32_t struct_version;
  enum DgDataType dtype;
  enum DgDataFormat format;
  enum DgDeviceKind device;
  size_t rank;
  size_t shape[8];
} DgTensorInfo;

/**
 * Release callback for imported raw external memory. It is invoked exactly once
 * when the library no longer references the external handle.
 */
typedef void (*DgReleaseCallback)(void*);

/**
 * External memory descriptor for v2 ABI imports.
 *
 * Exactly one of `fd` or `raw` must be valid. FD imports are duplicated; the
 * library closes the duplicate. Raw imports require a non-null release callback.
 */
typedef struct DgExternalMemoryV2 {
  uint32_t struct_size;
  uint32_t struct_version;
  int fd;
  uint64_t raw;
  int32_t domain;
  int32_t device;
  size_t size_bytes;
  DgReleaseCallback release;
  void *user_data;
} DgExternalMemoryV2;

/**
 * Borrowed UTF-8 string view. The caller keeps the underlying memory valid for
 * the duration of the ABI call.
 */
typedef struct DgStringView {
  const char *data;
  size_t len;
} DgStringView;

/**
 * Borrowed byte view. The caller keeps the underlying memory valid for the
 * duration of the ABI call.
 */
typedef struct DgByteView {
  const uint8_t *data;
  size_t len;
} DgByteView;

/**
 * Borrowed shape dimensions view. The caller keeps the underlying memory valid
 * for the duration of the ABI call.
 */
typedef struct DgShapeView {
  const size_t *dims;
  size_t rank;
} DgShapeView;

/**
 * Returns the package version as a static UTF-8 C string.
 */
const char *dg_version(void);

/**
 * Returns the stable C ABI version as a static UTF-8 C string.
 */
const char *dg_abi_version(void);

/**
 * Returns the diagnostic status code stored in an error handle.
 */
enum DgStatus dg_error_status(const struct DgError *error);

/**
 * Returns the error category (e.g. "InvalidArgument") as a stable UTF-8 C
 * string. The pointer is valid as long as `error` is not freed.
 */
const char *dg_error_category(const struct DgError *error);

/**
 * Returns the operation name associated with the error, or "Unknown".
 */
const char *dg_error_operation(const struct DgError *error);

/**
 * Returns the full human-readable error message.
 */
const char *dg_error_message(const struct DgError *error);

/**
 * Frees an error handle obtained from a fallible v2 ABI call.
 */
void dg_error_free(struct DgError *error);

/**
 * Returns a pointer to the owned byte buffer's contents.
 */
const uint8_t *dg_owned_bytes_data(const struct DgOwnedBytes *owned);

/**
 * Returns the length of the owned byte buffer in bytes.
 */
size_t dg_owned_bytes_len(const struct DgOwnedBytes *owned);

/**
 * Frees an owned byte handle obtained from a v2 ABI call.
 */
void dg_owned_bytes_free(struct DgOwnedBytes *owned);

/**
 * Returns a JSON object describing this build's C ABI capabilities.
 *
 * On success writes a `DgOwnedBytes` handle to `out`. On failure writes null
 * to `out` and, if non-null, an error handle to `out_error`.
 */
enum DgStatus dg_build_capabilities_json(struct DgOwnedBytes **out, struct DgError **out_error);

/**
 * Idempotent process-level runtime bootstrap (INT5-09).
 *
 * Installs built-in stream connectors when the `stream`/`cheetah` features are
 * enabled. `options` may be null for defaults; when non-null, `struct_size`
 * must match `sizeof(DgRuntimeInitOptions)`.
 */
enum DgStatus dg_runtime_init(const struct DgRuntimeInitOptions *options,
                              struct DgError **out_error);

/**
 * Creates an engine handle.
 */
enum DgStatus dg_engine_create(struct DgEngine **out, struct DgError **out_error);

/**
 * Destroys an engine handle with a timeout in milliseconds. Null is accepted.
 *
 * On success the handle is freed. If the running graph cannot be shut down
 * within `timeout_ms`, `DgStatus::Busy` is returned and the handle remains
 * valid so the caller can retry.
 */
enum DgStatus dg_engine_destroy(struct DgEngine *engine,
                                uint64_t timeout_ms,
                                struct DgError **out_error);

/**
 * Loads a graph specification from a UTF-8 string.
 */
enum DgStatus dg_engine_load_string(struct DgEngine *engine,
                                    int32_t format,
                                    const char *content,
                                    struct DgError **out_error);

/**
 * Loads a graph specification from a UTF-8 path.
 */
enum DgStatus dg_engine_load_file(struct DgEngine *engine,
                                  const char *path,
                                  struct DgError **out_error);

/**
 * Reloads a graph specification from a UTF-8 string.
 *
 * A built graph is updated in place and remains ready to run. Reload is rejected while inputs
 * are pending so that queued data is never silently interpreted by a changed graph.
 */
enum DgStatus dg_engine_reload_string(struct DgEngine *engine,
                                      int32_t format,
                                      const char *content,
                                      struct DgError **out_error);

/**
 * Reloads a graph specification from a UTF-8 path.
 *
 * A built graph is updated in place and remains ready to run. Reload is rejected while inputs
 * are pending so that queued data is never silently interpreted by a changed graph.
 */
enum DgStatus dg_engine_reload_file(struct DgEngine *engine,
                                    const char *path,
                                    struct DgError **out_error);

/**
 * Computes node and connection changes against a UTF-8 graph specification.
 */
enum DgStatus dg_engine_diff_string(const struct DgEngine *engine,
                                    int32_t format,
                                    const char *content,
                                    size_t *out_added_nodes,
                                    size_t *out_removed_nodes,
                                    size_t *out_updated_nodes,
                                    size_t *out_added_connections,
                                    size_t *out_removed_connections,
                                    struct DgError **out_error);

/**
 * Computes node and connection changes against a UTF-8 graph file.
 */
enum DgStatus dg_engine_diff_file(const struct DgEngine *engine,
                                  const char *path,
                                  size_t *out_added_nodes,
                                  size_t *out_removed_nodes,
                                  size_t *out_updated_nodes,
                                  size_t *out_added_connections,
                                  size_t *out_removed_connections,
                                  struct DgError **out_error);

/**
 * Adds a node programmatically. `params_json` may be null for an empty object.
 */
enum DgStatus dg_engine_add_node(struct DgEngine *engine,
                                 const char *name,
                                 const char *kind,
                                 const char *params_json,
                                 struct DgError **out_error);

/**
 * Removes a node by name and its incident connections.
 */
enum DgStatus dg_engine_remove_node(struct DgEngine *engine,
                                    const char *name,
                                    struct DgError **out_error);

/**
 * Adds a graph edge in `source.port -> destination.port` form.
 */
enum DgStatus dg_engine_connect(struct DgEngine *engine,
                                const char *connection,
                                struct DgError **out_error);

/**
 * Removes a graph edge.
 */
enum DgStatus dg_engine_disconnect(struct DgEngine *engine,
                                   const char *connection,
                                   struct DgError **out_error);

/**
 * Validates and builds the current graph specification.
 */
enum DgStatus dg_engine_build(struct DgEngine *engine, struct DgError **out_error);

/**
 * Runs the built graph with pending inputs and stores sink outputs for polling.
 */
enum DgStatus dg_engine_run(struct DgEngine *engine, struct DgError **out_error);

/**
 * Starts the engine as a long-running graph.
 */
enum DgStatus dg_engine_init(struct DgEngine *engine, struct DgError **out_error);

/**
 * Requests a cooperative stop of the running graph.
 */
enum DgStatus dg_engine_stop(struct DgEngine *engine, struct DgError **out_error);

/**
 * Shuts down the running graph with a timeout in milliseconds.
 */
enum DgStatus dg_engine_shutdown(struct DgEngine *engine,
                                 uint64_t timeout_ms,
                                 struct DgError **out_error);

/**
 * Returns the current lifecycle status of the engine. On success `out_status`
 * is written; if the status is `Failed` and `out_cause` is non-null, an owned
 * byte handle containing the root cause is written to `out_cause`.
 * On any error `out_status` is set to `DgGraphStatus::NotRunning`.
 */
enum DgStatus dg_engine_status(const struct DgEngine *engine,
                               enum DgGraphStatus *out_status,
                               struct DgOwnedBytes **out_cause,
                               struct DgError **out_error);

/**
 * Returns a JSON snapshot of per-element metrics as an owned byte handle.
 */
enum DgStatus dg_engine_metrics(const struct DgEngine *engine,
                                struct DgOwnedBytes **out,
                                struct DgError **out_error);

/**
 * Creates and initializes a backend without constructing a graph.
 */
enum DgStatus dg_backend_create(int32_t kind,
                                const uint8_t *model_data,
                                size_t model_length,
                                const char *options_json,
                                struct DgBackend **out,
                                struct DgError **out_error);

/**
 * Frees a direct backend handle. Null is accepted.
 */
void dg_backend_free(struct DgBackend *backend);

/**
 * Returns the number of backend inputs and outputs.
 */
enum DgStatus dg_backend_io_counts(const struct DgBackend *backend,
                                   size_t *out_inputs,
                                   size_t *out_outputs,
                                   struct DgError **out_error);

/**
 * Queries runtime device and precision capabilities.
 */
enum DgStatus dg_backend_capabilities(const struct DgBackend *backend,
                                      struct DgBackendCapabilities *out,
                                      struct DgError **out_error);

/**
 * Queries one input or output tensor description.
 */
enum DgStatus dg_backend_tensor_info(const struct DgBackend *backend,
                                     bool output,
                                     size_t index,
                                     struct DgTensorInfo *out,
                                     struct DgError **out_error);

/**
 * Runs direct backend inference over caller-owned tensor handles.
 */
enum DgStatus dg_backend_run(struct DgBackend *backend,
                             const struct DgTensor *const *inputs,
                             size_t input_count,
                             struct DgTensor **outputs,
                             size_t output_capacity,
                             size_t *out_count,
                             struct DgError **out_error);

/**
 * Creates a host tensor from a caller-owned byte array.
 */
enum DgStatus dg_tensor_create(const uint8_t *data,
                               size_t length,
                               const size_t *shape,
                               size_t rank,
                               int32_t dtype,
                               int32_t format,
                               int32_t device,
                               struct DgTensor **out,
                               struct DgError **out_error);

/**
 * Creates a tensor backed by an imported external buffer.
 */
enum DgStatus dg_tensor_create_external(const struct DgExternalMemoryV2 *desc,
                                        const size_t *shape,
                                        size_t rank,
                                        int32_t dtype,
                                        int32_t format,
                                        struct DgTensor **out,
                                        struct DgError **out_error);

/**
 * Frees a tensor handle. Null is accepted.
 */
void dg_tensor_free(struct DgTensor *tensor);

/**
 * Returns a copied tensor byte snapshot as an owned byte handle.
 */
enum DgStatus dg_tensor_data(const struct DgTensor *tensor,
                             struct DgOwnedBytes **out,
                             struct DgError **out_error);

/**
 * Pushes one tensor into the built graph.
 */
enum DgStatus dg_engine_push(struct DgEngine *engine,
                             const struct DgTensor *tensor,
                             struct DgError **out_error);

/**
 * Polls one output tensor. `Again` means the queue is empty.
 */
enum DgStatus dg_engine_poll(struct DgEngine *engine,
                             struct DgTensor **out,
                             struct DgError **out_error);

/**
 * Imports an external buffer handle without dereferencing the external address.
 */
enum DgStatus dg_buffer_import_external(const struct DgExternalMemoryV2 *desc,
                                        struct DgBuffer **out,
                                        struct DgError **out_error);

/**
 * Returns the logical size of an imported buffer.
 */
enum DgStatus dg_buffer_size(const struct DgBuffer *buffer,
                             size_t *out_size,
                             struct DgError **out_error);

/**
 * Frees an external buffer handle.
 */
void dg_buffer_free(struct DgBuffer *buffer);

#endif  /* DG_CAPI_H */
